// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type Options as Options2, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { AuthCookieLoginApiAuthLoginPostData, AuthCookieLoginApiAuthLoginPostErrors, AuthCookieLoginApiAuthLoginPostResponses, AuthCookieLogoutApiAuthLogoutPostData, AuthCookieLogoutApiAuthLogoutPostErrors, AuthCookieLogoutApiAuthLogoutPostResponses, ExportMarkdownApiResearchJobIdExportMarkdownGetData, ExportMarkdownApiResearchJobIdExportMarkdownGetErrors, ExportMarkdownApiResearchJobIdExportMarkdownGetResponses, ExportPdfApiResearchJobIdExportPdfGetData, ExportPdfApiResearchJobIdExportPdfGetErrors, ExportPdfApiResearchJobIdExportPdfGetResponses, GetReportApiResearchJobIdReportGetData, GetReportApiResearchJobIdReportGetErrors, GetReportApiResearchJobIdReportGetResponses, HealthHealthGetData, HealthHealthGetResponses, PreviewResearchApiResearchPreviewPostData, PreviewResearchApiResearchPreviewPostErrors, PreviewResearchApiResearchPreviewPostResponses, RegisterRegisterApiAuthRegisterPostData, RegisterRegisterApiAuthRegisterPostErrors, RegisterRegisterApiAuthRegisterPostResponses, StartResearchApiResearchPostData, StartResearchApiResearchPostErrors, StartResearchApiResearchPostResponses, UsersCurrentUserApiAuthUsersMeGetData, UsersCurrentUserApiAuthUsersMeGetErrors, UsersCurrentUserApiAuthUsersMeGetResponses, UsersDeleteUserApiAuthUsersIdDeleteData, UsersDeleteUserApiAuthUsersIdDeleteErrors, UsersDeleteUserApiAuthUsersIdDeleteResponses, UsersPatchCurrentUserApiAuthUsersMePatchData, UsersPatchCurrentUserApiAuthUsersMePatchErrors, UsersPatchCurrentUserApiAuthUsersMePatchResponses, UsersPatchUserApiAuthUsersIdPatchData, UsersPatchUserApiAuthUsersIdPatchErrors, UsersPatchUserApiAuthUsersIdPatchResponses, UsersUserApiAuthUsersIdGetData, UsersUserApiAuthUsersIdGetErrors, UsersUserApiAuthUsersIdGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Auth:Cookie.Login
 */
export const authCookieLoginApiAuthLoginPost = <ThrowOnError extends boolean = false>(options: Options<AuthCookieLoginApiAuthLoginPostData, ThrowOnError>) => (options.client ?? client).post<AuthCookieLoginApiAuthLoginPostResponses, AuthCookieLoginApiAuthLoginPostErrors, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers
    }
});

/**
 * Auth:Cookie.Logout
 */
export const authCookieLogoutApiAuthLogoutPost = <ThrowOnError extends boolean = false>(options?: Options<AuthCookieLogoutApiAuthLogoutPostData, ThrowOnError>) => (options?.client ?? client).post<AuthCookieLogoutApiAuthLogoutPostResponses, AuthCookieLogoutApiAuthLogoutPostErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'synapse_auth',
            type: 'apiKey'
        }],
    url: '/api/auth/logout',
    ...options
});

/**
 * Register:Register
 */
export const registerRegisterApiAuthRegisterPost = <ThrowOnError extends boolean = false>(options: Options<RegisterRegisterApiAuthRegisterPostData, ThrowOnError>) => (options.client ?? client).post<RegisterRegisterApiAuthRegisterPostResponses, RegisterRegisterApiAuthRegisterPostErrors, ThrowOnError>({
    url: '/api/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Users:Current User
 */
export const usersCurrentUserApiAuthUsersMeGet = <ThrowOnError extends boolean = false>(options?: Options<UsersCurrentUserApiAuthUsersMeGetData, ThrowOnError>) => (options?.client ?? client).get<UsersCurrentUserApiAuthUsersMeGetResponses, UsersCurrentUserApiAuthUsersMeGetErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'synapse_auth',
            type: 'apiKey'
        }],
    url: '/api/auth/users/me',
    ...options
});

/**
 * Users:Patch Current User
 */
export const usersPatchCurrentUserApiAuthUsersMePatch = <ThrowOnError extends boolean = false>(options: Options<UsersPatchCurrentUserApiAuthUsersMePatchData, ThrowOnError>) => (options.client ?? client).patch<UsersPatchCurrentUserApiAuthUsersMePatchResponses, UsersPatchCurrentUserApiAuthUsersMePatchErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'synapse_auth',
            type: 'apiKey'
        }],
    url: '/api/auth/users/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Users:Delete User
 */
export const usersDeleteUserApiAuthUsersIdDelete = <ThrowOnError extends boolean = false>(options: Options<UsersDeleteUserApiAuthUsersIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<UsersDeleteUserApiAuthUsersIdDeleteResponses, UsersDeleteUserApiAuthUsersIdDeleteErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'synapse_auth',
            type: 'apiKey'
        }],
    url: '/api/auth/users/{id}',
    ...options
});

/**
 * Users:User
 */
export const usersUserApiAuthUsersIdGet = <ThrowOnError extends boolean = false>(options: Options<UsersUserApiAuthUsersIdGetData, ThrowOnError>) => (options.client ?? client).get<UsersUserApiAuthUsersIdGetResponses, UsersUserApiAuthUsersIdGetErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'synapse_auth',
            type: 'apiKey'
        }],
    url: '/api/auth/users/{id}',
    ...options
});

/**
 * Users:Patch User
 */
export const usersPatchUserApiAuthUsersIdPatch = <ThrowOnError extends boolean = false>(options: Options<UsersPatchUserApiAuthUsersIdPatchData, ThrowOnError>) => (options.client ?? client).patch<UsersPatchUserApiAuthUsersIdPatchResponses, UsersPatchUserApiAuthUsersIdPatchErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'synapse_auth',
            type: 'apiKey'
        }],
    url: '/api/auth/users/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Start Research
 *
 * Persist a new research job and hand it off to the worker.
 *
 * The row is committed before the task is enqueued so the worker (which loads the job by id) is guaranteed to see it. If the enqueue fails the row is left in `pending`; a later sweep can either retry it or mark it as failed.
 */
export const startResearchApiResearchPost = <ThrowOnError extends boolean = false>(options: Options<StartResearchApiResearchPostData, ThrowOnError>) => (options.client ?? client).post<StartResearchApiResearchPostResponses, StartResearchApiResearchPostErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'synapse_auth',
            type: 'apiKey'
        }],
    url: '/api/research',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Preview Research
 *
 * Run only Scout's decompose step and return the proposed sub-questions.
 *
 * No job row is created and no work is queued. This is intentionally a
 * synchronous preview: the caller gets sub-questions back immediately so they
 * can review and drop them before committing to a full research run.
 */
export const previewResearchApiResearchPreviewPost = <ThrowOnError extends boolean = false>(options: Options<PreviewResearchApiResearchPreviewPostData, ThrowOnError>) => (options.client ?? client).post<PreviewResearchApiResearchPreviewPostResponses, PreviewResearchApiResearchPreviewPostErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'synapse_auth',
            type: 'apiKey'
        }],
    url: '/api/research/preview',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Report
 */
export const getReportApiResearchJobIdReportGet = <ThrowOnError extends boolean = false>(options: Options<GetReportApiResearchJobIdReportGetData, ThrowOnError>) => (options.client ?? client).get<GetReportApiResearchJobIdReportGetResponses, GetReportApiResearchJobIdReportGetErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'synapse_auth',
            type: 'apiKey'
        }],
    url: '/api/research/{job_id}/report',
    ...options
});

/**
 * Export Markdown
 */
export const exportMarkdownApiResearchJobIdExportMarkdownGet = <ThrowOnError extends boolean = false>(options: Options<ExportMarkdownApiResearchJobIdExportMarkdownGetData, ThrowOnError>) => (options.client ?? client).get<ExportMarkdownApiResearchJobIdExportMarkdownGetResponses, ExportMarkdownApiResearchJobIdExportMarkdownGetErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'synapse_auth',
            type: 'apiKey'
        }],
    url: '/api/research/{job_id}/export/markdown',
    ...options
});

/**
 * Export Pdf
 */
export const exportPdfApiResearchJobIdExportPdfGet = <ThrowOnError extends boolean = false>(options: Options<ExportPdfApiResearchJobIdExportPdfGetData, ThrowOnError>) => (options.client ?? client).get<ExportPdfApiResearchJobIdExportPdfGetResponses, ExportPdfApiResearchJobIdExportPdfGetErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'synapse_auth',
            type: 'apiKey'
        }],
    url: '/api/research/{job_id}/export/pdf',
    ...options
});

/**
 * Health
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });
