// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type Options as Options2, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { AuthCookieLoginApiAuthLoginPostData, AuthCookieLoginApiAuthLoginPostErrors, AuthCookieLoginApiAuthLoginPostResponses, AuthCookieLogoutApiAuthLogoutPostData, AuthCookieLogoutApiAuthLogoutPostErrors, AuthCookieLogoutApiAuthLogoutPostResponses, HealthHealthGetData, HealthHealthGetResponses, RegisterRegisterApiAuthRegisterPostData, RegisterRegisterApiAuthRegisterPostErrors, RegisterRegisterApiAuthRegisterPostResponses, StartResearchApiResearchPostData, StartResearchApiResearchPostErrors, StartResearchApiResearchPostResponses, UsersCurrentUserApiAuthUsersMeGetData, UsersCurrentUserApiAuthUsersMeGetErrors, UsersCurrentUserApiAuthUsersMeGetResponses, UsersDeleteUserApiAuthUsersIdDeleteData, UsersDeleteUserApiAuthUsersIdDeleteErrors, UsersDeleteUserApiAuthUsersIdDeleteResponses, UsersPatchCurrentUserApiAuthUsersMePatchData, UsersPatchCurrentUserApiAuthUsersMePatchErrors, UsersPatchCurrentUserApiAuthUsersMePatchResponses, UsersPatchUserApiAuthUsersIdPatchData, UsersPatchUserApiAuthUsersIdPatchErrors, UsersPatchUserApiAuthUsersIdPatchResponses, UsersUserApiAuthUsersIdGetData, UsersUserApiAuthUsersIdGetErrors, UsersUserApiAuthUsersIdGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Auth:Cookie.Login
 */
export const authCookieLoginApiAuthLoginPost = <ThrowOnError extends boolean = false>(options: Options<AuthCookieLoginApiAuthLoginPostData, ThrowOnError>) => (options.client ?? client).post<AuthCookieLoginApiAuthLoginPostResponses, AuthCookieLoginApiAuthLoginPostErrors, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers
    }
});

/**
 * Auth:Cookie.Logout
 */
export const authCookieLogoutApiAuthLogoutPost = <ThrowOnError extends boolean = false>(options?: Options<AuthCookieLogoutApiAuthLogoutPostData, ThrowOnError>) => (options?.client ?? client).post<AuthCookieLogoutApiAuthLogoutPostResponses, AuthCookieLogoutApiAuthLogoutPostErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'synapse_auth',
            type: 'apiKey'
        }],
    url: '/api/auth/logout',
    ...options
});

/**
 * Register:Register
 */
export const registerRegisterApiAuthRegisterPost = <ThrowOnError extends boolean = false>(options: Options<RegisterRegisterApiAuthRegisterPostData, ThrowOnError>) => (options.client ?? client).post<RegisterRegisterApiAuthRegisterPostResponses, RegisterRegisterApiAuthRegisterPostErrors, ThrowOnError>({
    url: '/api/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Users:Current User
 */
export const usersCurrentUserApiAuthUsersMeGet = <ThrowOnError extends boolean = false>(options?: Options<UsersCurrentUserApiAuthUsersMeGetData, ThrowOnError>) => (options?.client ?? client).get<UsersCurrentUserApiAuthUsersMeGetResponses, UsersCurrentUserApiAuthUsersMeGetErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'synapse_auth',
            type: 'apiKey'
        }],
    url: '/api/auth/users/me',
    ...options
});

/**
 * Users:Patch Current User
 */
export const usersPatchCurrentUserApiAuthUsersMePatch = <ThrowOnError extends boolean = false>(options: Options<UsersPatchCurrentUserApiAuthUsersMePatchData, ThrowOnError>) => (options.client ?? client).patch<UsersPatchCurrentUserApiAuthUsersMePatchResponses, UsersPatchCurrentUserApiAuthUsersMePatchErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'synapse_auth',
            type: 'apiKey'
        }],
    url: '/api/auth/users/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Users:Delete User
 */
export const usersDeleteUserApiAuthUsersIdDelete = <ThrowOnError extends boolean = false>(options: Options<UsersDeleteUserApiAuthUsersIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<UsersDeleteUserApiAuthUsersIdDeleteResponses, UsersDeleteUserApiAuthUsersIdDeleteErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'synapse_auth',
            type: 'apiKey'
        }],
    url: '/api/auth/users/{id}',
    ...options
});

/**
 * Users:User
 */
export const usersUserApiAuthUsersIdGet = <ThrowOnError extends boolean = false>(options: Options<UsersUserApiAuthUsersIdGetData, ThrowOnError>) => (options.client ?? client).get<UsersUserApiAuthUsersIdGetResponses, UsersUserApiAuthUsersIdGetErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'synapse_auth',
            type: 'apiKey'
        }],
    url: '/api/auth/users/{id}',
    ...options
});

/**
 * Users:Patch User
 */
export const usersPatchUserApiAuthUsersIdPatch = <ThrowOnError extends boolean = false>(options: Options<UsersPatchUserApiAuthUsersIdPatchData, ThrowOnError>) => (options.client ?? client).patch<UsersPatchUserApiAuthUsersIdPatchResponses, UsersPatchUserApiAuthUsersIdPatchErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'synapse_auth',
            type: 'apiKey'
        }],
    url: '/api/auth/users/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Start Research
 *
 * Queue a new research job.
 *
 * TODO: persist job to DB, push to taskiq, hand off to orchestrator.
 */
export const startResearchApiResearchPost = <ThrowOnError extends boolean = false>(options: Options<StartResearchApiResearchPostData, ThrowOnError>) => (options.client ?? client).post<StartResearchApiResearchPostResponses, StartResearchApiResearchPostErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'synapse_auth',
            type: 'apiKey'
        }],
    url: '/api/research',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Health
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });
