// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_auth_cookie_login_api_auth_login_post
 */
export type BodyAuthCookieLoginApiAuthLoginPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ClaimFlag
 */
export type ClaimFlag = {
    /**
     * Claim Id
     */
    claim_id: string;
    /**
     * Section Id
     */
    section_id: string;
    verdict: Verdict;
    /**
     * Rationale
     */
    rationale: string;
    /**
     * Supporting Source Ids
     */
    supporting_source_ids: Array<string>;
};

/**
 * Contradiction
 */
export type Contradiction = {
    /**
     * Description
     */
    description: string;
    /**
     * Source Ids
     */
    source_ids: Array<string>;
};

/**
 * CriticAnnotations
 */
export type CriticAnnotations = {
    /**
     * Id
     */
    id: string;
    /**
     * Report Id
     */
    report_id: string;
    /**
     * Section Confidence
     */
    section_confidence: Array<SectionConfidence>;
    /**
     * Claim Flags
     */
    claim_flags: Array<ClaimFlag>;
    /**
     * Overall Confidence
     */
    overall_confidence: number;
    /**
     * Model
     */
    model: string;
    /**
     * Generated At
     */
    generated_at: string;
};

/**
 * Depth
 */
export type Depth = 'shallow' | 'standard' | 'deep';

/**
 * ErrorModel
 */
export type ErrorModel = {
    /**
     * Detail
     */
    detail: string | {
        [key: string]: string;
    };
};

/**
 * FollowUpLink
 *
 * One edge in a job's follow-up lineage.
 *
 * `job_id` / `topic` / `status` describe the job on the *other* end of the edge (the parent when this link is a job's parent, a child when it is one of a job's children); `question` is the follow-up question recorded on the edge itself.
 */
export type FollowUpLink = {
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Question
     */
    question: string;
    /**
     * Topic
     */
    topic: string;
    status: JobStatus;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * FollowUpRequest
 *
 * Inbound body for POST /api/research/{job_id}/follow-up.
 *
 * The child job inherits language, depth, and per-agent models from the parent, so the only thing the caller supplies is the new question.
 */
export type FollowUpRequest = {
    /**
     * Question
     */
    question: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * JobLineage
 *
 * Response body for GET /api/research/{job_id}/lineage.
 */
export type JobLineage = {
    parent: FollowUpLink | null;
    /**
     * Children
     */
    children: Array<FollowUpLink>;
};

/**
 * JobStatus
 */
export type JobStatus = 'pending' | 'scouting' | 'synthesizing' | 'critiquing' | 'completed' | 'failed';

/**
 * PreviewResponse
 *
 * Response body for POST /api/research/preview.
 */
export type PreviewResponse = {
    /**
     * Sub Questions
     */
    sub_questions: Array<string>;
};

/**
 * ReportSection
 */
export type ReportSection = {
    /**
     * Id
     */
    id: string;
    /**
     * Heading
     */
    heading: string;
    /**
     * Body Md
     */
    body_md: string;
    /**
     * Cited Source Ids
     */
    cited_source_ids?: Array<string>;
};

/**
 * ResearchJob
 *
 * Job descriptor returned to the client on creation and status queries.
 */
export type ResearchJob = {
    /**
     * Id
     */
    id: string;
    /**
     * Topic
     */
    topic: string;
    /**
     * Language
     */
    language?: string;
    depth?: Depth;
    /**
     * Models
     */
    models?: {
        [key: string]: string;
    };
    /**
     * Sub Questions
     */
    sub_questions?: Array<string> | null;
    status?: JobStatus;
    /**
     * Progress
     */
    progress?: number;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Updated At
     */
    updated_at?: string;
    /**
     * Completed At
     */
    completed_at?: string | null;
};

/**
 * ResearchRequest
 *
 * Inbound request body for POST /api/research.
 */
export type ResearchRequest = {
    /**
     * Topic
     */
    topic: string;
    /**
     * Language
     */
    language?: string;
    depth?: Depth;
    /**
     * Models
     */
    models: {
        [key: string]: string;
    };
    /**
     * Sub Questions
     */
    sub_questions?: Array<string> | null;
};

/**
 * ScribeReport
 */
export type ScribeReport = {
    /**
     * Id
     */
    id: string;
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Topic
     */
    topic: string;
    /**
     * Title
     */
    title: string;
    /**
     * Summary Md
     */
    summary_md: string;
    /**
     * Sections
     */
    sections: Array<ReportSection>;
    /**
     * Sources
     */
    sources: Array<Source>;
    /**
     * Contradictions
     */
    contradictions: Array<Contradiction>;
    /**
     * Follow Ups
     */
    follow_ups: Array<string>;
    /**
     * Generated At
     */
    generated_at: string;
    /**
     * Model
     */
    model: string;
};

/**
 * SectionConfidence
 */
export type SectionConfidence = {
    /**
     * Section Id
     */
    section_id: string;
    /**
     * Score
     */
    score: number;
    /**
     * Reasoning
     */
    reasoning: string;
};

/**
 * Source
 *
 * A single source gathered by Scout, referenced by Scribe and Critic.
 */
export type Source = {
    /**
     * Id
     */
    id: string;
    /**
     * Url
     */
    url: string;
    /**
     * Title
     */
    title: string;
    /**
     * Author
     */
    author?: string | null;
    /**
     * Published At
     */
    published_at?: string | null;
    /**
     * Credibility
     */
    credibility: number;
    /**
     * Relevance
     */
    relevance: number;
    /**
     * Snippet
     */
    snippet: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Is Verified
     */
    is_verified?: boolean | null;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Is Verified
     */
    is_verified?: boolean;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Password
     */
    password?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Is Verified
     */
    is_verified?: boolean | null;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Verdict
 */
export type Verdict = 'supported' | 'partially_supported' | 'unsupported' | 'contradicted';

/**
 * VerifiedReport
 *
 * Full response returned to the frontend once a job has completed.
 */
export type VerifiedReport = {
    job: ResearchJob;
    report: ScribeReport;
    annotations: CriticAnnotations;
};

/**
 * ClaimVerified
 */
export type ClaimVerified = {
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Timestamp
     */
    timestamp?: string;
    /**
     * Type
     */
    type: 'claim_verified';
    flag: ClaimFlag;
};

/**
 * JobCompleted
 */
export type JobCompleted = {
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Timestamp
     */
    timestamp?: string;
    /**
     * Type
     */
    type: 'job_completed';
    /**
     * Overall Confidence
     */
    overall_confidence: number;
};

/**
 * JobFailed
 */
export type JobFailed = {
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Timestamp
     */
    timestamp?: string;
    /**
     * Type
     */
    type: 'job_failed';
    /**
     * Error
     */
    error: string;
};

/**
 * ScoutComplete
 */
export type ScoutComplete = {
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Timestamp
     */
    timestamp?: string;
    /**
     * Type
     */
    type: 'scout_complete';
    /**
     * Source Count
     */
    source_count: number;
};

/**
 * ScribeComplete
 */
export type ScribeComplete = {
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Timestamp
     */
    timestamp?: string;
    /**
     * Type
     */
    type: 'scribe_complete';
};

/**
 * SectionDrafted
 */
export type SectionDrafted = {
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Timestamp
     */
    timestamp?: string;
    /**
     * Type
     */
    type: 'section_drafted';
    section: ReportSection;
};

/**
 * SourceFound
 */
export type SourceFound = {
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Timestamp
     */
    timestamp?: string;
    /**
     * Type
     */
    type: 'source_found';
    source: Source;
};

/**
 * SourceScored
 */
export type SourceScored = {
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Timestamp
     */
    timestamp?: string;
    /**
     * Type
     */
    type: 'source_scored';
    /**
     * Source Id
     */
    source_id: string;
    /**
     * Credibility
     */
    credibility: number;
    /**
     * Relevance
     */
    relevance: number;
};

/**
 * SubQuestionsGenerated
 */
export type SubQuestionsGenerated = {
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Timestamp
     */
    timestamp?: string;
    /**
     * Type
     */
    type: 'sub_questions_generated';
    /**
     * Sub Questions
     */
    sub_questions: Array<string>;
};

export type ProgressEvent = ({
    type: 'sub_questions_generated';
} & SubQuestionsGenerated) | ({
    type: 'source_found';
} & SourceFound) | ({
    type: 'source_scored';
} & SourceScored) | ({
    type: 'scout_complete';
} & ScoutComplete) | ({
    type: 'section_drafted';
} & SectionDrafted) | ({
    type: 'scribe_complete';
} & ScribeComplete) | ({
    type: 'claim_verified';
} & ClaimVerified) | ({
    type: 'job_completed';
} & JobCompleted) | ({
    type: 'job_failed';
} & JobFailed);

/**
 * JobSnapshot
 *
 * First message sent on a WebSocket connection.
 *
 * Lets a client that connected mid-pipeline render the current state instead of waiting for the next event.
 * `job` is optional so callers can still emit an identity-only snapshot when no persisted job state is available.
 */
export type JobSnapshot = {
    /**
     * Type
     */
    type: 'snapshot';
    /**
     * Job Id
     */
    job_id: string;
    job?: ResearchJob | null;
};

export type AuthCookieLoginApiAuthLoginPostData = {
    body: BodyAuthCookieLoginApiAuthLoginPost;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type AuthCookieLoginApiAuthLoginPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthCookieLoginApiAuthLoginPostError = AuthCookieLoginApiAuthLoginPostErrors[keyof AuthCookieLoginApiAuthLoginPostErrors];

export type AuthCookieLoginApiAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
    /**
     * No Content
     */
    204: void;
};

export type AuthCookieLoginApiAuthLoginPostResponse = AuthCookieLoginApiAuthLoginPostResponses[keyof AuthCookieLoginApiAuthLoginPostResponses];

export type AuthCookieLogoutApiAuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type AuthCookieLogoutApiAuthLogoutPostErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
};

export type AuthCookieLogoutApiAuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
    /**
     * No Content
     */
    204: void;
};

export type AuthCookieLogoutApiAuthLogoutPostResponse = AuthCookieLogoutApiAuthLogoutPostResponses[keyof AuthCookieLogoutApiAuthLogoutPostResponses];

export type RegisterRegisterApiAuthRegisterPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterRegisterApiAuthRegisterPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterRegisterApiAuthRegisterPostError = RegisterRegisterApiAuthRegisterPostErrors[keyof RegisterRegisterApiAuthRegisterPostErrors];

export type RegisterRegisterApiAuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    201: UserRead;
};

export type RegisterRegisterApiAuthRegisterPostResponse = RegisterRegisterApiAuthRegisterPostResponses[keyof RegisterRegisterApiAuthRegisterPostResponses];

export type UsersCurrentUserApiAuthUsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/users/me';
};

export type UsersCurrentUserApiAuthUsersMeGetErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
};

export type UsersCurrentUserApiAuthUsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersCurrentUserApiAuthUsersMeGetResponse = UsersCurrentUserApiAuthUsersMeGetResponses[keyof UsersCurrentUserApiAuthUsersMeGetResponses];

export type UsersPatchCurrentUserApiAuthUsersMePatchData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/api/auth/users/me';
};

export type UsersPatchCurrentUserApiAuthUsersMePatchErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersPatchCurrentUserApiAuthUsersMePatchError = UsersPatchCurrentUserApiAuthUsersMePatchErrors[keyof UsersPatchCurrentUserApiAuthUsersMePatchErrors];

export type UsersPatchCurrentUserApiAuthUsersMePatchResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersPatchCurrentUserApiAuthUsersMePatchResponse = UsersPatchCurrentUserApiAuthUsersMePatchResponses[keyof UsersPatchCurrentUserApiAuthUsersMePatchResponses];

export type UsersDeleteUserApiAuthUsersIdDeleteData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/auth/users/{id}';
};

export type UsersDeleteUserApiAuthUsersIdDeleteErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserApiAuthUsersIdDeleteError = UsersDeleteUserApiAuthUsersIdDeleteErrors[keyof UsersDeleteUserApiAuthUsersIdDeleteErrors];

export type UsersDeleteUserApiAuthUsersIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UsersDeleteUserApiAuthUsersIdDeleteResponse = UsersDeleteUserApiAuthUsersIdDeleteResponses[keyof UsersDeleteUserApiAuthUsersIdDeleteResponses];

export type UsersUserApiAuthUsersIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/auth/users/{id}';
};

export type UsersUserApiAuthUsersIdGetErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUserApiAuthUsersIdGetError = UsersUserApiAuthUsersIdGetErrors[keyof UsersUserApiAuthUsersIdGetErrors];

export type UsersUserApiAuthUsersIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersUserApiAuthUsersIdGetResponse = UsersUserApiAuthUsersIdGetResponses[keyof UsersUserApiAuthUsersIdGetResponses];

export type UsersPatchUserApiAuthUsersIdPatchData = {
    body: UserUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/auth/users/{id}';
};

export type UsersPatchUserApiAuthUsersIdPatchErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersPatchUserApiAuthUsersIdPatchError = UsersPatchUserApiAuthUsersIdPatchErrors[keyof UsersPatchUserApiAuthUsersIdPatchErrors];

export type UsersPatchUserApiAuthUsersIdPatchResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersPatchUserApiAuthUsersIdPatchResponse = UsersPatchUserApiAuthUsersIdPatchResponses[keyof UsersPatchUserApiAuthUsersIdPatchResponses];

export type StartResearchApiResearchPostData = {
    body: ResearchRequest;
    path?: never;
    query?: never;
    url: '/api/research';
};

export type StartResearchApiResearchPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartResearchApiResearchPostError = StartResearchApiResearchPostErrors[keyof StartResearchApiResearchPostErrors];

export type StartResearchApiResearchPostResponses = {
    /**
     * Successful Response
     */
    202: ResearchJob;
};

export type StartResearchApiResearchPostResponse = StartResearchApiResearchPostResponses[keyof StartResearchApiResearchPostResponses];

export type PreviewResearchApiResearchPreviewPostData = {
    body: ResearchRequest;
    path?: never;
    query?: never;
    url: '/api/research/preview';
};

export type PreviewResearchApiResearchPreviewPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PreviewResearchApiResearchPreviewPostError = PreviewResearchApiResearchPreviewPostErrors[keyof PreviewResearchApiResearchPreviewPostErrors];

export type PreviewResearchApiResearchPreviewPostResponses = {
    /**
     * Successful Response
     */
    200: PreviewResponse;
};

export type PreviewResearchApiResearchPreviewPostResponse = PreviewResearchApiResearchPreviewPostResponses[keyof PreviewResearchApiResearchPreviewPostResponses];

export type StartFollowUpApiResearchJobIdFollowUpPostData = {
    body: FollowUpRequest;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/research/{job_id}/follow-up';
};

export type StartFollowUpApiResearchJobIdFollowUpPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartFollowUpApiResearchJobIdFollowUpPostError = StartFollowUpApiResearchJobIdFollowUpPostErrors[keyof StartFollowUpApiResearchJobIdFollowUpPostErrors];

export type StartFollowUpApiResearchJobIdFollowUpPostResponses = {
    /**
     * Successful Response
     */
    202: ResearchJob;
};

export type StartFollowUpApiResearchJobIdFollowUpPostResponse = StartFollowUpApiResearchJobIdFollowUpPostResponses[keyof StartFollowUpApiResearchJobIdFollowUpPostResponses];

export type GetJobLineageApiResearchJobIdLineageGetData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/research/{job_id}/lineage';
};

export type GetJobLineageApiResearchJobIdLineageGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobLineageApiResearchJobIdLineageGetError = GetJobLineageApiResearchJobIdLineageGetErrors[keyof GetJobLineageApiResearchJobIdLineageGetErrors];

export type GetJobLineageApiResearchJobIdLineageGetResponses = {
    /**
     * Successful Response
     */
    200: JobLineage;
};

export type GetJobLineageApiResearchJobIdLineageGetResponse = GetJobLineageApiResearchJobIdLineageGetResponses[keyof GetJobLineageApiResearchJobIdLineageGetResponses];

export type GetReportApiResearchJobIdReportGetData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/research/{job_id}/report';
};

export type GetReportApiResearchJobIdReportGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetReportApiResearchJobIdReportGetError = GetReportApiResearchJobIdReportGetErrors[keyof GetReportApiResearchJobIdReportGetErrors];

export type GetReportApiResearchJobIdReportGetResponses = {
    /**
     * Successful Response
     */
    200: VerifiedReport;
};

export type GetReportApiResearchJobIdReportGetResponse = GetReportApiResearchJobIdReportGetResponses[keyof GetReportApiResearchJobIdReportGetResponses];

export type ExportMarkdownApiResearchJobIdExportMarkdownGetData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/research/{job_id}/export/markdown';
};

export type ExportMarkdownApiResearchJobIdExportMarkdownGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportMarkdownApiResearchJobIdExportMarkdownGetError = ExportMarkdownApiResearchJobIdExportMarkdownGetErrors[keyof ExportMarkdownApiResearchJobIdExportMarkdownGetErrors];

export type ExportMarkdownApiResearchJobIdExportMarkdownGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExportPdfApiResearchJobIdExportPdfGetData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/research/{job_id}/export/pdf';
};

export type ExportPdfApiResearchJobIdExportPdfGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportPdfApiResearchJobIdExportPdfGetError = ExportPdfApiResearchJobIdExportPdfGetErrors[keyof ExportPdfApiResearchJobIdExportPdfGetErrors];

export type ExportPdfApiResearchJobIdExportPdfGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Response Health Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];
