"""create initial schema

Revision ID: 0f956ea0001f
Revises:
Create Date: 2026-05-07 21:12:26.265903

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f956ea0001f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "research_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("language", sa.String(), server_default="en", nullable=False),
        sa.Column("depth", sa.String(), server_default="standard", nullable=False),
        sa.Column("models", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(), server_default="pending", nullable=False),
        sa.Column("progress", sa.Float(), server_default="0", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_research_jobs_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_jobs")),
    )
    op.create_index(op.f("ix_research_jobs_status"), "research_jobs", ["status"], unique=False)
    op.create_index(op.f("ix_research_jobs_user_id"), "research_jobs", ["user_id"], unique=False)
    op.create_table(
        "follow_ups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("parent_job_id", sa.Uuid(), nullable=False),
        sa.Column("child_job_id", sa.Uuid(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["child_job_id"],
            ["research_jobs.id"],
            name=op.f("fk_follow_ups_child_job_id_research_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_job_id"],
            ["research_jobs.id"],
            name=op.f("fk_follow_ups_parent_job_id_research_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_follow_ups")),
    )
    op.create_index(
        op.f("ix_follow_ups_child_job_id"), "follow_ups", ["child_job_id"], unique=False
    )
    op.create_index(
        op.f("ix_follow_ups_parent_job_id"), "follow_ups", ["parent_job_id"], unique=False
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary_md", sa.Text(), nullable=False),
        sa.Column("body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("generated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["research_jobs.id"],
            name=op.f("fk_reports_job_id_research_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
        sa.UniqueConstraint("job_id", name=op.f("uq_reports_job_id")),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("short_id", sa.String(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column("published_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("snippet", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("credibility", sa.Float(), nullable=False),
        sa.Column("relevance", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["research_jobs.id"],
            name=op.f("fk_sources_job_id_research_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("job_id", "short_id", name="uq_sources_job_id_short_id"),
        sa.UniqueConstraint("job_id", "url", name="uq_sources_job_id_url"),
    )
    op.create_index(op.f("ix_sources_job_id"), "sources", ["job_id"], unique=False)
    op.create_table(
        "critic_annotations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("overall_confidence", sa.Float(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("generated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
            name=op.f("fk_critic_annotations_report_id_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_critic_annotations")),
        sa.UniqueConstraint("report_id", name=op.f("uq_critic_annotations_report_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("critic_annotations")
    op.drop_index(op.f("ix_sources_job_id"), table_name="sources")
    op.drop_table("sources")
    op.drop_table("reports")
    op.drop_index(op.f("ix_follow_ups_parent_job_id"), table_name="follow_ups")
    op.drop_index(op.f("ix_follow_ups_child_job_id"), table_name="follow_ups")
    op.drop_table("follow_ups")
    op.drop_index(op.f("ix_research_jobs_user_id"), table_name="research_jobs")
    op.drop_index(op.f("ix_research_jobs_status"), table_name="research_jobs")
    op.drop_table("research_jobs")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
