"""add sub_questions_override to research_jobs

Revision ID: 7b2ef9c8bcca
Revises: 0f956ea0001f
Create Date: 2026-05-09 00:09:31.198493

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b2ef9c8bcca"
down_revision: str | Sequence[str] | None = "0f956ea0001f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "research_jobs",
        sa.Column("sub_questions_override", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("research_jobs", "sub_questions_override")
    # ### end Alembic commands ###
